create table search_users_data_ucos_4_2 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	email VARCHAR(255),
	gender VARCHAR(255),
	address VARCHAR(255),
	state VARCHAR(255),
	nationality VARCHAR(255),
	car_brand VARCHAR(255),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (1, 'Darrin', 'Fawlks', 'dfawlks0@xinhuanet.com', 'Male', '1st Floor', 'Villa Paula de Sarmiento', 'Argentina', 'Ford', '2024-05-09 22:12:22');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (2, 'Cindi', 'Baily', 'cbaily1@tripod.com', 'Female', 'Room 485', 'Wosai', 'China', 'Acura', '2024-06-17 03:17:53');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (3, 'Caressa', 'Amerighi', 'camerighi2@mit.edu', 'Female', 'Room 123', 'Noyemberyan', 'Armenia', 'Audi', '2024-10-23 19:16:05');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (4, 'Mufi', 'Lisett', 'mlisett3@pagesperso-orange.fr', 'Female', '16th Floor', 'Räpina', 'Estonia', 'Volkswagen', '2024-09-09 19:48:10');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (5, 'Yvon', 'Fendt', 'yfendt4@who.int', 'Male', '7th Floor', 'Ujmisht', 'Albania', 'Mitsubishi', '2024-04-19 19:25:56');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (6, 'Bert', 'Filipychev', 'bfilipychev5@abc.net.au', 'Male', 'PO Box 43044', 'Hashimoto', 'Japan', 'Lexus', '2024-02-22 02:38:49');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (7, 'Juliana', 'Ashlee', 'jashlee6@stanford.edu', 'Female', 'Room 213', 'Yug', 'Russia', 'Nissan', '2024-09-18 22:49:52');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (8, 'Elfrieda', 'Deshorts', 'edeshorts7@a8.net', 'Female', 'Suite 24', 'Thị Trấn Tà Lùng', 'Vietnam', 'Honda', '2024-07-24 22:34:56');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (9, 'Kiel', 'Sacks', 'ksacks8@ihg.com', 'Male', 'PO Box 22222', 'Annecy', 'France', 'BMW', '2024-01-25 22:26:12');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (10, 'Ike', 'Laguerre', 'ilaguerre9@economist.com', 'Male', 'Suite 78', 'Huangtan', 'China', 'Kia', '2024-01-15 11:59:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (11, 'Sawyer', 'Redholes', 'sredholesa@google.com.au', 'Male', 'Room 1103', 'Trollhättan', 'Sweden', 'Dodge', '2024-04-01 23:09:30');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (12, 'Pincas', 'Halton', 'phaltonb@ustream.tv', 'Male', 'Apt 649', 'Pulau Pinang', 'Malaysia', 'Mazda', '2023-12-21 03:40:44');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (13, 'Eustacia', 'Jansky', 'ejanskyc@cafepress.com', 'Female', 'Room 598', 'Uzlovaya', 'Russia', 'Maybach', '2024-01-03 23:26:29');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (14, 'Sarina', 'Rummery', 'srummeryd@earthlink.net', 'Genderfluid', 'Room 1922', 'Limen', 'China', 'Lamborghini', '2024-07-30 18:41:11');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (15, 'Marshall', 'Naisbet', 'mnaisbete@ameblo.jp', 'Male', 'Suite 18', 'Abaca', 'Philippines', 'GMC', '2024-02-22 06:13:30');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (16, 'Beth', 'Spataro', 'bspatarof@qq.com', 'Female', 'Apt 426', 'Pangkalan', 'Indonesia', 'Ford', '2024-01-02 17:59:58');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (17, 'Goraud', 'Pennigar', 'gpennigarg@dmoz.org', 'Male', 'Room 1449', 'Buenos Aires', 'Peru', 'Chevrolet', '2024-05-14 02:23:24');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (18, 'Colby', 'Ledgard', 'cledgardh@csmonitor.com', 'Male', 'Room 1399', 'Seiça', 'Portugal', 'Daihatsu', '2023-12-22 06:30:44');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (19, 'Rochella', 'MacLaverty', 'rmaclavertyi@elegantthemes.com', 'Female', 'Apt 776', 'Jintang', 'China', 'Chevrolet', '2024-04-24 23:57:33');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (20, 'Joscelin', 'Balbeck', 'jbalbeckj@google.es', 'Female', 'PO Box 6345', 'Hidalgo', 'Mexico', 'Toyota', '2024-03-25 20:11:51');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (21, 'Dusty', 'Fife', 'dfifek@goodreads.com', 'Female', 'Apt 1905', 'Novogurovskiy', 'Russia', 'Ford', '2024-07-23 12:06:19');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (22, 'Marylynne', 'Niblett', 'mniblettl@youku.com', 'Female', '6th Floor', 'Santa Cruz', 'Mexico', 'Infiniti', '2024-06-06 17:57:35');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (23, 'Erik', 'Yushin', 'eyushinm@toplist.cz', 'Male', 'Room 1660', 'Ponyri Vtoryye', 'Russia', 'Scion', '2024-06-13 09:49:21');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (24, 'Dot', 'Vallintine', 'dvallintinen@sina.com.cn', 'Female', 'Room 445', 'Kokar', 'Indonesia', 'Infiniti', '2024-03-14 05:10:44');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (25, 'Alford', 'Eberlein', 'aeberleino@sohu.com', 'Male', 'PO Box 20531', 'Palmira', 'Colombia', 'BMW', '2023-11-23 01:53:20');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (26, 'Iorgos', 'McCaffrey', 'imccaffreyp@ycombinator.com', 'Male', 'PO Box 36227', 'Sumberrejo', 'Indonesia', 'Toyota', '2024-07-26 21:46:21');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (27, 'Berton', 'Janecki', 'bjaneckiq@blogspot.com', 'Male', '20th Floor', 'Rungis', 'France', 'Toyota', '2024-10-12 15:02:53');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (28, 'Talyah', 'Gally', 'tgallyr@digg.com', 'Female', 'PO Box 99485', 'Zongzhai', 'China', 'Land Rover', '2024-07-21 12:26:54');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (29, 'Farrand', 'Elsbury', 'felsburys@hp.com', 'Female', '19th Floor', 'La Caya', 'Dominican Republic', 'Toyota', '2024-05-27 02:48:10');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (30, 'Jud', 'Kauschke', 'jkauschket@rediff.com', 'Male', 'Suite 44', 'Nueva Germania', 'Paraguay', 'Ford', '2024-04-08 20:37:17');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (31, 'Austine', 'Cottell', 'acottellu@webeden.co.uk', 'Female', 'Apt 1124', 'Comendador', 'Dominican Republic', 'Nissan', '2024-02-29 06:04:15');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (32, 'Bordie', 'O''Crevy', 'bocrevyv@hexun.com', 'Male', 'PO Box 88319', 'Saint Augustine', 'United States', 'Honda', '2024-06-14 21:45:00');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (33, 'Shalom', 'Mayou', 'smayouw@squidoo.com', 'Male', 'Suite 86', 'Xinli', 'China', 'Eagle', '2024-07-04 02:22:54');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (34, 'Anne', 'Blacklock', 'ablacklockx@ebay.co.uk', 'Bigender', 'Room 660', 'Villeneuve-la-Garenne', 'France', 'GMC', '2024-09-10 06:26:47');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (35, 'Tobit', 'Parsonson', 'tparsonsony@sitemeter.com', 'Genderqueer', '6th Floor', 'Maxixe', 'Mozambique', 'Saab', '2024-04-18 14:29:10');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (36, 'Bernardina', 'Swepstone', 'bswepstonez@naver.com', 'Female', 'PO Box 37983', 'Padamulya', 'Indonesia', 'Ford', '2023-12-02 18:09:34');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (37, 'Petronilla', 'Dautry', 'pdautry10@nps.gov', 'Female', 'PO Box 29895', 'Obas', 'Peru', 'Volkswagen', '2024-04-18 20:40:42');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (38, 'Anni', 'Cordell', 'acordell11@shop-pro.jp', 'Female', 'Suite 48', 'Kalmar', 'Sweden', 'Land Rover', '2024-03-17 20:32:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (39, 'Eunice', 'Gogie', 'egogie12@edublogs.org', 'Female', 'Suite 83', 'Whitegate', 'Ireland', 'Isuzu', '2024-08-02 00:48:35');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (40, 'Poppy', 'Burmaster', 'pburmaster13@squarespace.com', 'Female', 'PO Box 33711', 'Aranos', 'Namibia', 'Subaru', '2024-03-23 08:30:31');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (41, 'Fonzie', 'Howsin', 'fhowsin14@elpais.com', 'Male', 'Apt 448', 'Pom Prap Sattru Phai', 'Thailand', 'Lincoln', '2024-05-19 11:36:19');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (42, 'Paolina', 'Le Batteur', 'plebatteur15@bbc.co.uk', 'Female', 'Apt 1624', 'Shanggu', 'China', 'Chevrolet', '2024-06-04 06:01:05');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (43, 'Brianne', 'O'' Gara', 'bogara16@barnesandnoble.com', 'Agender', 'PO Box 89737', 'Dalududalu', 'Indonesia', 'Kia', '2024-07-29 21:40:29');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (44, 'Kimberly', 'McElrath', 'kmcelrath17@yelp.com', 'Female', 'Room 1808', 'Dniprodzerzhyns’k', 'Ukraine', 'Suzuki', '2024-08-20 10:45:28');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (45, 'Ingram', 'Pache', 'ipache18@pcworld.com', 'Genderfluid', 'Suite 52', 'Kumane', 'Serbia', 'Lincoln', '2023-12-06 13:54:58');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (46, 'Christiana', 'Giraths', 'cgiraths19@posterous.com', 'Female', 'Room 1381', 'Xiuyu', 'China', 'Mazda', '2024-01-01 18:55:59');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (47, 'Tamarah', 'Simmonite', 'tsimmonite1a@cloudflare.com', 'Female', 'PO Box 81151', 'Vanáton', 'Greece', 'Toyota', '2024-01-20 20:29:28');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (48, 'Shani', 'Brauninger', 'sbrauninger1b@hibu.com', 'Female', 'Suite 33', 'Stepanivka', 'Ukraine', 'Land Rover', '2023-12-04 02:46:57');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (49, 'Heinrick', 'Gollin', 'hgollin1c@foxnews.com', 'Male', 'PO Box 51799', 'Cà Mau', 'Vietnam', 'Mercury', '2023-11-05 08:18:53');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (50, 'Jemie', 'Livingston', 'jlivingston1d@omniture.com', 'Female', '6th Floor', 'Carrigaline', 'Ireland', 'Nissan', '2024-08-20 12:37:58');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (51, 'Emma', 'Behrens', 'ebehrens1e@ameblo.jp', 'Female', 'Room 309', 'Santa Catarina Barahona', 'Guatemala', 'Jeep', '2024-10-12 14:31:21');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (52, 'Kiley', 'Saunper', 'ksaunper1f@about.com', 'Polygender', 'Room 1017', 'Uppsala', 'Sweden', 'GMC', '2024-07-15 10:18:43');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (53, 'Celisse', 'Tonnesen', 'ctonnesen1g@jimdo.com', 'Female', 'Apt 1215', 'Papatowai', 'New Zealand', 'Studebaker', '2024-06-23 14:47:27');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (54, 'Alfredo', 'Kittow', 'akittow1h@freewebs.com', 'Male', 'PO Box 26337', 'Balzar', 'Ecuador', 'Ford', '2024-06-27 12:36:42');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (55, 'Kass', 'Clemmens', 'kclemmens1i@nih.gov', 'Female', 'Room 1697', 'Kołaczyce', 'Poland', 'Ford', '2023-12-02 00:22:58');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (56, 'Francis', 'Connue', 'fconnue1j@surveymonkey.com', 'Male', 'PO Box 48518', 'Zwierzyń', 'Poland', 'Hummer', '2023-12-18 13:54:14');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (57, 'Theresita', 'Bedlington', 'tbedlington1k@com.com', 'Female', 'Room 1867', 'Bom Jesus da Lapa', 'Brazil', 'Chevrolet', '2024-02-26 00:11:08');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (58, 'Hasty', 'Frew', 'hfrew1l@netvibes.com', 'Male', '4th Floor', 'Stockholm', 'Sweden', 'Dodge', '2024-04-09 05:49:23');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (59, 'Gottfried', 'Ashley', 'gashley1m@nymag.com', 'Male', 'Suite 98', 'Lao Suea Kok', 'Thailand', 'Subaru', '2024-06-30 06:43:08');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (60, 'Jammie', 'Butte', 'jbutte1n@un.org', 'Female', 'PO Box 5688', 'Brudzew', 'Poland', 'Dodge', '2024-04-15 13:41:53');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (61, 'Shem', 'Leckenby', 'sleckenby1o@globo.com', 'Male', 'Room 173', 'Manhuaçu', 'Brazil', 'Suzuki', '2024-04-17 03:04:37');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (62, 'Audre', 'Rubinovitch', 'arubinovitch1p@prlog.org', 'Female', 'Room 339', 'Zográfos', 'Greece', 'Oldsmobile', '2024-07-25 17:44:16');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (63, 'Gerry', 'Ranby', 'granby1q@cisco.com', 'Female', 'Apt 1990', 'Shuangqiaoping', 'China', 'Nissan', '2023-11-26 18:50:08');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (64, 'Tani', 'Storm', 'tstorm1r@wufoo.com', 'Female', 'Suite 12', 'Randu', 'Indonesia', 'Volkswagen', '2024-02-18 09:38:03');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (65, 'Bentley', 'Dales', 'bdales1s@ycombinator.com', 'Male', 'Room 1728', 'Monjarás', 'Honduras', 'Bentley', '2024-10-16 15:41:50');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (66, 'Simon', 'Weber', 'sweber1t@bravesites.com', 'Male', 'Apt 1160', 'Havířov', 'Czech Republic', 'Buick', '2024-01-16 06:47:02');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (67, 'Lucien', 'Le Surf', 'llesurf1u@nymag.com', 'Male', 'PO Box 82551', 'Lugang', 'China', 'Pontiac', '2023-12-29 21:58:18');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (68, 'Alleen', 'Gosenell', 'agosenell1v@nhs.uk', 'Female', 'PO Box 79827', 'Ualog', 'Philippines', 'Dodge', '2024-04-24 10:24:15');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (69, 'Daria', 'Dibdall', 'ddibdall1w@dion.ne.jp', 'Female', 'Room 1154', 'Vladimirskaya', 'Russia', 'Volkswagen', '2023-12-27 15:15:35');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (70, 'Jolene', 'Oldford', 'joldford1x@people.com.cn', 'Female', '12th Floor', 'Wuying', 'China', 'Honda', '2024-05-30 11:46:50');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (71, 'Loree', 'Eltringham', 'leltringham1y@cornell.edu', 'Female', 'PO Box 76411', 'Dandai', 'China', 'Ford', '2024-04-19 01:31:35');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (72, 'Hobie', 'Shorbrook', 'hshorbrook1z@example.com', 'Male', 'Apt 1508', 'Vila Pouca da Beira', 'Portugal', 'Dodge', '2024-03-03 10:10:09');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (73, 'Shelia', 'Genner', 'sgenner20@paypal.com', 'Female', '7th Floor', 'São José do Egito', 'Brazil', 'Infiniti', '2024-03-27 23:41:37');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (74, 'Alonzo', 'Peye', 'apeye21@ask.com', 'Male', 'PO Box 86350', 'Miguel Hidalgo', 'Mexico', 'Mitsubishi', '2024-05-17 22:44:00');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (75, 'Rennie', 'O'' Donohue', 'rodonohue22@noaa.gov', 'Female', 'Apt 1820', 'Jiehu', 'China', 'Mazda', '2024-05-13 23:55:30');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (76, 'Amata', 'Cains', 'acains23@squidoo.com', 'Female', 'Room 995', 'Dongke', 'China', 'Buick', '2024-06-06 05:31:25');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (77, 'Ogdan', 'Ferrant', 'oferrant24@apple.com', 'Male', 'Room 36', 'Kadurahayu', 'Indonesia', 'Honda', '2024-02-11 00:28:21');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (78, 'Savina', 'Livezey', 'slivezey25@theatlantic.com', 'Female', 'PO Box 55029', 'Kalinkavichy', 'Belarus', 'Cadillac', '2024-06-11 21:53:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (79, 'Salomon', 'Clemanceau', 'sclemanceau26@networksolutions.com', 'Bigender', '20th Floor', 'Ķegums', 'Latvia', 'Dodge', '2024-06-29 20:26:45');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (80, 'Shannon', 'Marquez', 'smarquez27@yellowpages.com', 'Non-binary', 'Room 1117', 'Huyang', 'China', 'Mazda', '2024-06-05 01:24:50');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (81, 'Ange', 'Cahani', 'acahani28@unblog.fr', 'Female', 'PO Box 99432', 'Nowe Grocholice', 'Poland', 'Mercedes-Benz', '2024-03-21 01:41:43');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (82, 'Lon', 'Clapison', 'lclapison29@phoca.cz', 'Male', 'Apt 1234', 'Bureya', 'Russia', 'Chevrolet', '2024-08-18 10:20:38');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (83, 'Rand', 'Mirando', 'rmirando2a@delicious.com', 'Male', 'Apt 886', 'Ke’erlun', 'China', 'Acura', '2024-09-03 12:44:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (84, 'Rip', 'Baccus', 'rbaccus2b@unicef.org', 'Male', 'Apt 1092', 'Crasto', 'Portugal', 'Volkswagen', '2024-07-15 15:06:19');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (85, 'Cristiano', 'Etchells', 'cetchells2c@flickr.com', 'Male', 'Room 1435', 'Chabany', 'Ukraine', 'Acura', '2023-11-06 08:55:06');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (86, 'Colleen', 'Stone Fewings', 'cstonefewings2d@alexa.com', 'Female', '9th Floor', 'Kubangwaru', 'Indonesia', 'Audi', '2024-03-13 03:33:56');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (87, 'Geordie', 'Dreng', 'gdreng2e@princeton.edu', 'Polygender', 'PO Box 20485', 'Talisay', 'Philippines', 'Toyota', '2024-05-20 17:36:53');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (88, 'Fairfax', 'Kilgour', 'fkilgour2f@about.me', 'Male', 'Apt 1571', 'Vitrolles', 'France', 'Lexus', '2024-04-30 23:54:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (89, 'Elvin', 'MacPhaden', 'emacphaden2g@amazon.com', 'Male', '1st Floor', 'Banjar Desa', 'Indonesia', 'Toyota', '2024-07-20 18:42:48');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (90, 'Zonda', 'Jenne', 'zjenne2h@jugem.jp', 'Female', 'Room 125', 'Lunao', 'Philippines', 'Chevrolet', '2024-10-12 14:02:22');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (91, 'Marwin', 'Castagnasso', 'mcastagnasso2i@paypal.com', 'Male', '3rd Floor', 'Luzino', 'Poland', 'MINI', '2024-03-14 04:23:39');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (92, 'Tedman', 'Asaaf', 'tasaaf2j@prweb.com', 'Male', 'Suite 75', 'Melchor de Mencos', 'Guatemala', 'Chevrolet', '2024-01-24 01:23:59');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (93, 'Bridgette', 'Ellesmere', 'bellesmere2k@people.com.cn', 'Female', 'Suite 1', 'Paleran', 'Indonesia', 'Mercedes-Benz', '2023-11-05 22:33:57');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (94, 'Inglis', 'Greystock', 'igreystock2l@ask.com', 'Male', 'Suite 1', 'Masingbi', 'Sierra Leone', 'Jaguar', '2024-08-06 11:13:22');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (95, 'Temp', 'Georgiades', 'tgeorgiades2m@furl.net', 'Male', 'Apt 895', 'Hisor', 'Tajikistan', 'Acura', '2024-02-29 00:00:29');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (96, 'Jonathon', 'Sellack', 'jsellack2n@pcworld.com', 'Male', '11th Floor', 'Syntul', 'Russia', 'Ford', '2024-06-25 14:32:35');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (97, 'Desi', 'Raulin', 'draulin2o@rambler.ru', 'Male', 'PO Box 51656', 'Chunyang', 'China', 'Chevrolet', '2024-02-01 01:27:12');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (98, 'Iseabal', 'Kluss', 'ikluss2p@mashable.com', 'Female', 'Apt 297', 'Sarany', 'Russia', 'Lincoln', '2023-12-09 03:00:47');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (99, 'Benyamin', 'Boome', 'bboome2q@google.de', 'Male', '4th Floor', 'Maradi', 'Niger', 'Porsche', '2024-10-09 06:03:50');
insert into search_users_data_ucos_4_2 (id, first_name, last_name, email, gender, address, state, nationality, car_brand, date_added) values (100, 'Carlita', 'Gusticke', 'cgusticke2r@foxnews.com', 'Female', '3rd Floor', 'Warung Wetan', 'Indonesia', 'Chevrolet', '2024-03-12 17:57:55');