create table agrilands (
	farmland_id INT AUTO_INCREMENT PRIMARY KEY,
	farm_name VARCHAR(50),
	location VARCHAR(50),
	crop_type VARCHAR(50),
	owner VARCHAR(50),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (1, 'Spinka-Dickens', 'Florida', 'Streblus', 'Raynell MacTrustam', '2025-09-27 14:01:34');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (2, 'Lebsack Group', 'Florida', 'Myrosma', 'Robinett Colbertson', '2025-01-03 05:51:29');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (3, 'Klocko-Lesch', 'Florida', 'Brewer''s Lupine', 'Allie Ellis', '2025-09-01 09:14:22');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (4, 'Feest, Wehner and Wyman', 'California', 'Virginia Strawberry', 'Beverlie Goodee', '2025-07-27 10:56:12');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (5, 'Hermann-Metz', 'California', 'Mancos Columbine', 'Lenci Wakefield', '2024-10-22 17:23:42');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (6, 'Predovic, Jenkins and McClure', 'California', 'Whorled Rosinweed', 'Tammie Wheway', '2025-06-30 08:11:00');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (7, 'Gusikowski, Breitenberg and Ortiz', 'Washington', 'Redclaws', 'Asher Dellenty', '2025-01-06 19:11:08');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (8, 'Fisher-Jacobs', 'Georgia', 'Barrelier''s Woodsorrel', 'Roxine Purvey', '2025-06-21 10:52:17');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (9, 'Muller Group', 'Virginia', 'Appalachian Barren Strawberry', 'Giacinta Gallahue', '2025-09-20 20:20:29');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (10, 'Corkery, Gusikowski and Hartmann', 'Ohio', 'Curvedleaf Ulota Moss', 'Mychal Livesley', '2025-09-29 07:17:27');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (11, 'Grimes-Schmitt', 'New York', 'Mexicali Onion', 'Nadiya Di Maggio', '2025-02-18 08:32:29');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (12, 'Mraz, Wolff and Schultz', 'Massachusetts', 'Mojave Mound Cactus', 'Prue Chastel', '2024-12-10 11:34:50');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (13, 'Bechtelar LLC', 'California', 'Porter''s Melicgrass', 'Burton Filmer', '2025-08-01 17:42:44');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (14, 'Rosenbaum Inc', 'Florida', 'Flower''s Orthotrichum Moss', 'Jeff Trevallion', '2025-02-05 11:39:19');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (15, 'Fisher-Jenkins', 'California', 'Simarouba', 'Vonni Bangley', '2025-06-17 19:28:17');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (16, 'Wisozk Group', 'Florida', 'Porpidia Lichen', 'Alecia Rickaert', '2025-07-22 01:08:14');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (17, 'Goldner, Orn and Nikolaus', 'Oklahoma', 'Wild Coffee-bean', 'Jennifer Giurio', '2025-07-05 10:15:55');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (18, 'Moore and Sons', 'Nebraska', 'Carolina Larkspur', 'Val Grigoriscu', '2025-05-28 23:40:35');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (19, 'Abernathy and Sons', 'Indiana', 'Dianella', 'Jabez Pucker', '2025-07-28 14:37:23');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (20, 'Zulauf, Cartwright and Beahan', 'Massachusetts', 'New Mexico Starviolet', 'Agna Wilshaw', '2025-05-23 00:08:29');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (21, 'Conn, Streich and Roob', 'New Jersey', 'Pomegranate', 'Ram Grahame', '2025-03-12 03:28:28');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (22, 'McDermott, Gleason and Terry', 'New York', 'Caracas Pepper', 'Sophia Beteriss', '2024-10-16 19:44:18');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (23, 'Kiehn-Kshlerin', 'Indiana', 'Witch''s Hair Lichen', 'Arabella McDermid', '2025-07-18 09:27:33');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (24, 'Rice, Leannon and Ward', 'Alabama', 'Douglas'' Bladderfern', 'Adelbert Cheake', '2025-05-01 19:45:35');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (25, 'Emard-Murphy', 'Florida', 'Fameflower', 'Dion McClifferty', '2025-02-10 03:05:38');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (26, 'Spinka-Morissette', 'Ohio', 'Dwarf Peashrub', 'Devlen Grassi', '2025-04-04 18:25:35');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (27, 'Erdman LLC', 'Wisconsin', 'Schimper''s Campylopus Moss', 'Frannie Mcmanaman', '2025-08-15 19:21:31');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (28, 'Cronin, Spencer and Leuschke', 'Washington', 'Whitewhorl Lupine', 'Brandie Gilling', '2025-02-20 17:25:28');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (29, 'Zulauf-Fisher', 'Indiana', 'Mottled Tuberose', 'Lazare Burtwistle', '2024-12-08 10:48:59');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (30, 'Mayert-Schuppe', 'Washington', 'Tall Thimbleweed', 'Raye Adamovsky', '2024-11-17 10:43:08');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (31, 'DuBuque, Grant and Spencer', 'Georgia', 'Cashew', 'Tyne Rutty', '2025-03-18 07:39:37');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (32, 'Satterfield-Quigley', 'Arizona', 'Longleaf Buchu', 'Gilemette Emlyn', '2024-11-08 12:41:36');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (33, 'Quitzon LLC', 'Massachusetts', 'Mountain Pepperweed', 'Julius Pawelczyk', '2025-09-13 04:15:01');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (34, 'Vandervort, Legros and Hoeger', 'Colorado', 'Torrey''s Sedge', 'Elijah Rayson', '2024-11-05 03:02:54');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (35, 'Connelly-Lind', 'New York', 'Littleleaf Milkwort', 'Gusti Bevington', '2025-01-24 13:24:39');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (36, 'Stehr Inc', 'District of Columbia', 'Western Juniper', 'Yalonda Stourton', '2025-06-02 23:14:40');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (37, 'Kassulke, Dickens and Crooks', 'Michigan', 'Langsdorf''s Lousewort', 'Priscilla Franceschielli', '2024-12-14 22:09:51');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (38, 'Streich-Champlin', 'Iowa', 'Bracted Sulphur Lichen', 'Silvia O''Doherty', '2025-01-31 21:41:09');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (39, 'Mitchell, Sanford and Oberbrunner', 'Mississippi', 'Smartweed Leaf-flower', 'Adrianne Stolberg', '2025-07-18 11:43:11');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (40, 'Hickle, Friesen and Larkin', 'Pennsylvania', 'Fraternal Indian Paintbrush', 'Bobbie Birdis', '2024-12-09 13:55:39');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (41, 'Welch Inc', 'Oklahoma', 'Pseudoleskea Moss', 'Ellerey Tomeo', '2025-01-19 01:24:39');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (42, 'Schulist Group', 'North Dakota', 'Fleshy Starwort', 'Obediah Babbs', '2025-09-30 09:50:40');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (43, 'O''Conner LLC', 'Idaho', 'Pitted Onion', 'Beret Pyett', '2024-10-20 00:11:44');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (44, 'Rolfson and Sons', 'California', 'Tripleleaf Morning-glory', 'Holmes Dooly', '2024-11-23 02:29:29');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (45, 'O''Kon, Murazik and Jacobi', 'California', 'Cape Pondweed', 'Keeley Armstrong', '2025-02-15 13:46:46');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (46, 'Wiegand-Ledner', 'Arizona', 'Sarita Rosette Grass', 'Rebe Longmead', '2025-02-02 02:12:47');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (47, 'Witting-Grady', 'Iowa', 'Ponderosa Violet', 'Harriet Davitt', '2025-05-26 21:57:53');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (48, 'Heller-Denesik', 'Alabama', 'Greater Swinecress', 'Wilhelmine Barenski', '2025-03-05 10:00:49');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (49, 'Armstrong LLC', 'Iowa', 'White-mahogany', 'Cthrine Mabey', '2024-12-18 08:05:02');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (50, 'Schroeder and Sons', 'Illinois', 'Louisiana Lecidea Lichen', 'Tierney Leither', '2025-02-12 16:03:59');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (51, 'Upton-Price', 'Nevada', 'San Diego Povertyweed', 'Genovera Yatman', '2025-03-19 12:29:24');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (52, 'Champlin, Metz and Friesen', 'Texas', 'Pepperbush', 'Haze Doxsey', '2025-07-13 11:07:57');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (53, 'Satterfield, Braun and Steuber', 'Washington', 'Micromitrium Moss', 'Thaxter Southcoat', '2025-06-01 08:23:49');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (54, 'Lind, Klein and Predovic', 'New York', 'Bactrospora Lichen', 'Sutherlan Sydenham', '2025-05-28 10:55:25');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (55, 'McGlynn, Windler and Considine', 'California', 'Pitcherplant', 'Maryrose Ayrton', '2025-07-07 06:53:00');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (56, 'Wyman, Bode and Hansen', 'New York', 'Disc Lichen', 'Gabriellia Lashford', '2024-10-11 22:28:52');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (57, 'Stehr, Douglas and Christiansen', 'Texas', 'Queen Anne''s Lace', 'Bevan Godfree', '2025-07-19 17:30:03');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (58, 'Osinski Inc', 'Minnesota', 'Pitcherplant', 'Leif todor', '2025-08-26 07:56:53');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (59, 'Kuhlman-Hauck', 'Florida', 'Rush Lemonweed', 'Rosanna Epilet', '2025-06-29 11:46:43');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (60, 'Grady, Runolfsson and Cummings', 'Iowa', 'Sierra Biscuitroot', 'Ingar Cardenas', '2025-07-14 08:50:53');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (61, 'Rath-Braun', 'District of Columbia', 'Purple Poppymallow', 'Osbourne Bryden', '2025-07-16 23:15:57');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (62, 'Watsica-Ankunding', 'Texas', 'Whitetop', 'Meta Ducket', '2025-10-05 15:53:44');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (63, 'Rau-Murazik', 'Wisconsin', 'Flattened Pipewort', 'Nessi Acuna', '2024-12-25 15:19:33');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (64, 'Green and Sons', 'Alaska', 'Giantchickweed', 'Abbye Dunseath', '2025-08-16 04:00:04');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (65, 'Durgan Group', 'Kentucky', 'Tobacco', 'Irma Verdey', '2025-06-01 15:40:18');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (66, 'Botsford, Goyette and Parker', 'New York', 'Snow Currant', 'Gilberte Gwinnel', '2024-10-27 01:08:47');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (67, 'Lind Group', 'Texas', 'Galleta Grass', 'Clemmy Carlson', '2025-01-08 14:04:09');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (68, 'Dibbert-Emard', 'Mississippi', 'Blisterwort', 'Ferdie Eard', '2025-01-02 18:41:57');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (69, 'McCullough-Reinger', 'California', 'Roundleaf Sundew', 'Teresina Maykin', '2024-11-11 11:14:48');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (70, 'White-Schmeler', 'North Carolina', 'Twisted Spikerush', 'Solomon Pelz', '2025-01-10 03:24:59');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (71, 'Hamill-Huels', 'Pennsylvania', 'Baltimore Flavoparmelia Lichen', 'Elka Blofeld', '2025-05-04 21:22:51');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (72, 'MacGyver-Klocko', 'Arkansas', 'Oahu Pohe Hiwa', 'Dyanna Mullin', '2025-03-19 00:21:25');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (73, 'Olson, Schumm and Langworth', 'California', 'Plitt''s Xanthoparmelia Lichen', 'Basilius Gillman', '2025-03-28 15:22:36');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (74, 'Heidenreich, Marquardt and Heathcote', 'California', 'Desert Unicorn-plant', 'Monique Snary', '2024-12-15 01:15:48');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (75, 'Schumm-Sawayn', 'Utah', 'Plumed Rockcap Fern', 'Melicent Pawelski', '2025-07-14 11:43:32');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (76, 'Rice-Williamson', 'Maryland', 'Luisierella Moss', 'Kort Cerith', '2025-04-20 10:30:33');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (77, 'Collins, Daugherty and Will', 'Florida', 'Dune Tetramolopium', 'Guido Cripps', '2025-07-17 08:22:51');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (78, 'Flatley, Emard and Wisoky', 'Ohio', 'Alva Day''s Gilia', 'Kaycee Percifer', '2025-03-12 03:05:17');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (79, 'O''Keefe and Sons', 'Arizona', 'Salpiglossis', 'Heinrick Shynn', '2025-01-02 08:13:52');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (80, 'Yost, Vandervort and Kris', 'Florida', 'Egyptian Panicgrass', 'Xena Ellingsworth', '2025-06-20 06:04:24');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (81, 'Marvin, Ratke and Schiller', 'New York', 'Dallisgrass', 'Nancy Matys', '2025-01-24 16:21:18');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (82, 'Funk, Bogisich and Lakin', 'Florida', 'Longleaf Buchu', 'Cate Sara', '2025-05-20 12:14:55');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (83, 'Wiegand and Sons', 'Iowa', 'Spiked Wild Indigo', 'Whitman Stroban', '2025-05-03 04:15:17');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (84, 'Schimmel-West', 'New York', 'Collins'' Rockcress', 'Trixi Jedryka', '2025-06-05 01:30:26');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (85, 'Grady Group', 'California', 'Spanish Lime', 'Hewe Jeromson', '2025-01-07 21:12:53');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (86, 'Morar-Lesch', 'Ohio', 'Hawai''i Birdnest Fern', 'Bogart Goundry', '2025-01-03 20:12:23');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (87, 'Hauck-Wilderman', 'Colorado', 'Burroweed', 'Ardyce Gregersen', '2024-12-02 17:56:19');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (88, 'Bradtke-Ondricka', 'Georgia', 'Midsorus Fern', 'Teodoro Olohan', '2025-01-30 07:11:31');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (89, 'Monahan, Hessel and Rohan', 'Pennsylvania', 'New Mexican Nightshade', 'Charmian Gabby', '2025-06-10 02:45:53');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (90, 'Waters-Trantow', 'North Carolina', 'Fringed Yelloweyed Grass', 'Vita Strephan', '2025-01-12 06:03:08');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (91, 'Dooley LLC', 'Florida', 'Waianae Range Starviolet', 'Carita Eastup', '2025-08-05 10:32:18');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (92, 'Padberg-Blanda', 'California', 'Showy Sedge', 'Bayard Castelot', '2025-08-28 01:02:30');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (93, 'Langworth-Gulgowski', 'Florida', 'Borsch Stonecrop', 'Cathie Giurio', '2025-09-18 02:44:59');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (94, 'Hills-Schmitt', 'South Carolina', 'Fourleaf Mare''s-tail', 'Kasper Haggata', '2025-05-03 21:05:18');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (95, 'Konopelski, Braun and Ernser', 'Missouri', 'Appalachian False Goat''s Beard', 'Bay Foakes', '2025-08-24 19:03:17');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (96, 'Kunze LLC', 'Mississippi', 'Niihau Panicgrass', 'Rhetta Robinson', '2024-10-16 08:10:52');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (97, 'Swift LLC', 'North Carolina', 'Wahatoya Creek Larkspur', 'Beryl Mudie', '2025-04-01 09:47:20');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (98, 'Purdy-Johnston', 'California', 'Eucladium Moss', 'Guy Buckthorp', '2025-03-01 13:16:03');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (99, 'Koelpin, Jast and Conroy', 'California', 'Vetivergrass', 'Dayle Yeld', '2025-01-22 05:10:00');
insert into agrilands (farmland_id, farm_name, location, crop_type, owner, date_added) values (100, 'Quitzon Inc', 'Kentucky', 'Shingleplant', 'Gino Durning', '2024-12-01 17:25:10');
